export const teamsData = {
  109: {
    id: 109,
    name: "Arizona Diamondbacks",
    shortName: "D-backs",
    abbreviation: "AZ",
    divisionId: 203,
    divisionName: "NL West",
    leagueId: 104,
    primaryColor: "#A71930",
    secondaryColor: "#E3D4AD",
    textColor: "#FFFFFF"
  },
  144: {
    id: 144,
    name: "Atlanta Braves",
    shortName: "Braves",
    abbreviation: "ATL",
    divisionId: 204,
    divisionName: "NL East",
    leagueId: 104,
    primaryColor: "#13274F",
    secondaryColor: "#CE1141",
    textColor: "#FFFFFF"
  },
  110: {
    id: 110,
    name: "Baltimore Orioles",
    shortName: "Orioles",
    abbreviation: "BAL",
    divisionId: 201,
    divisionName: "AL East",
    leagueId: 103,
    primaryColor: "#DF4601",
    secondaryColor: "#000000",
    textColor: "#FFFFFF"
  },
  111: {
    id: 111,
    name: "Boston Red Sox",
    shortName: "Red Sox",
    abbreviation: "BOS",
    divisionId: 201,
    divisionName: "AL East",
    leagueId: 103,
    primaryColor: "#BD3039",
    secondaryColor: "#0C2340",
    textColor: "#FFFFFF"
  },
  112: {
    id: 112,
    name: "Chicago Cubs",
    shortName: "Cubs",
    abbreviation: "CHC",
    divisionId: 205,
    divisionName: "NL Central",
    leagueId: 104,
    primaryColor: "#0E3386",
    secondaryColor: "#CC3433",
    textColor: "#FFFFFF"
  },
  113: {
    id: 113,
    name: "Cincinnati Reds",
    shortName: "Reds",
    abbreviation: "CIN",
    divisionId: 205,
    divisionName: "NL Central",
    leagueId: 104,
    primaryColor: "#C6011F",
    secondaryColor: "#000000",
    textColor: "#FFFFFF"
  },
  114: {
    id: 114,
    name: "Cleveland Guardians",
    shortName: "Guardians",
    abbreviation: "CLE",
    divisionId: 202,
    divisionName: "AL Central",
    leagueId: 103,
    primaryColor: "#0C2340",
    secondaryColor: "#E31937",
    textColor: "#FFFFFF"
  },
  115: {
    id: 115,
    name: "Colorado Rockies",
    shortName: "Rockies",
    abbreviation: "COL",
    divisionId: 203,
    divisionName: "NL West",
    leagueId: 104,
    primaryColor: "#33006F",
    secondaryColor: "#C4CED4",
    textColor: "#FFFFFF"
  },
  145: {
    id: 145,
    name: "Chicago White Sox",
    shortName: "White Sox",
    abbreviation: "CWS",
    divisionId: 202,
    divisionName: "AL Central",
    leagueId: 103,
    primaryColor: "#27251F",
    secondaryColor: "#C4CED4",
    textColor: "#FFFFFF"
  },
  116: {
    id: 116,
    name: "Detroit Tigers",
    shortName: "Tigers",
    abbreviation: "DET",
    divisionId: 202,
    divisionName: "AL Central",
    leagueId: 103,
    primaryColor: "#0C2340",
    secondaryColor: "#FA4616",
    textColor: "#FFFFFF"
  },
  117: {
    id: 117,
    name: "Houston Astros",
    shortName: "Astros",
    abbreviation: "HOU",
    divisionId: 200,
    divisionName: "AL West",
    leagueId: 103,
    primaryColor: "#002D62",
    secondaryColor: "#EB6E1F",
    textColor: "#FFFFFF"
  },
  118: {
    id: 118,
    name: "Kansas City Royals",
    shortName: "Royals",
    abbreviation: "KC",
    divisionId: 202,
    divisionName: "AL Central",
    leagueId: 103,
    primaryColor: "#004687",
    secondaryColor: "#C5B076",
    textColor: "#FFFFFF"
  },
  108: {
    id: 108,
    name: "Los Angeles Angels",
    shortName: "Angels",
    abbreviation: "LAA",
    divisionId: 200,
    divisionName: "AL West",
    leagueId: 103,
    primaryColor: "#BA0021",
    secondaryColor: "#003263",
    textColor: "#FFFFFF"
  },
  119: {
    id: 119,
    name: "Los Angeles Dodgers",
    shortName: "Dodgers",
    abbreviation: "LAD",
    divisionId: 203,
    divisionName: "NL West",
    leagueId: 104,
    primaryColor: "#005A9C",
    secondaryColor: "#A5ACAF",
    textColor: "#FFFFFF"
  },
  146: {
    id: 146,
    name: "Miami Marlins",
    shortName: "Marlins",
    abbreviation: "MIA",
    divisionId: 204,
    divisionName: "NL East",
    leagueId: 104,
    primaryColor: "#00A3E0",
    secondaryColor: "#EF3340",
    textColor: "#FFFFFF"
  },
  158: {
    id: 158,
    name: "Milwaukee Brewers",
    shortName: "Brewers",
    abbreviation: "MIL",
    divisionId: 205,
    divisionName: "NL Central",
    leagueId: 104,
    primaryColor: "#12284C",
    secondaryColor: "#FFC52F",
    textColor: "#FFFFFF"
  },
  142: {
    id: 142,
    name: "Minnesota Twins",
    shortName: "Twins",
    abbreviation: "MIN",
    divisionId: 202,
    divisionName: "AL Central",
    leagueId: 103,
    primaryColor: "#002B5C",
    secondaryColor: "#D31145",
    textColor: "#FFFFFF"
  },
  121: {
    id: 121,
    name: "New York Mets",
    shortName: "Mets",
    abbreviation: "NYM",
    divisionId: 204,
    divisionName: "NL East",
    leagueId: 104,
    primaryColor: "#002D72",
    secondaryColor: "#FF5910",
    textColor: "#FFFFFF"
  },
  147: {
    id: 147,
    name: "New York Yankees",
    shortName: "Yankees",
    abbreviation: "NYY",
    divisionId: 201,
    divisionName: "AL East",
    leagueId: 103,
    primaryColor: "#0C2340",
    secondaryColor: "#C4CED4",
    textColor: "#FFFFFF"
  },
  133: {
    id: 133,
    name: "Athletics",
    shortName: "Athletics",
    abbreviation: "ATH",
    divisionId: 200,
    divisionName: "AL West",
    leagueId: 103,
    primaryColor: "#003831",
    secondaryColor: "#EFB21E",
    textColor: "#FFFFFF"
  },
  143: {
    id: 143,
    name: "Philadelphia Phillies",
    shortName: "Phillies",
    abbreviation: "PHI",
    divisionId: 204,
    divisionName: "NL East",
    leagueId: 104,
    primaryColor: "#E81828",
    secondaryColor: "#284898",
    textColor: "#FFFFFF"
  },
  134: {
    id: 134,
    name: "Pittsburgh Pirates",
    shortName: "Pirates",
    abbreviation: "PIT",
    divisionId: 205,
    divisionName: "NL Central",
    leagueId: 104,
    primaryColor: "#27251F",
    secondaryColor: "#FDB827",
    textColor: "#000000"
  },
  135: {
    id: 135,
    name: "San Diego Padres",
    shortName: "Padres",
    abbreviation: "SD",
    divisionId: 203,
    divisionName: "NL West",
    leagueId: 104,
    primaryColor: "#2F241D",
    secondaryColor: "#FFC425",
    textColor: "#FFFFFF"
  },
  136: {
    id: 136,
    name: "Seattle Mariners",
    shortName: "Mariners",
    abbreviation: "SEA",
    divisionId: 200,
    divisionName: "AL West",
    leagueId: 103,
    primaryColor: "#0C2C56",
    secondaryColor: "#005C5C",
    textColor: "#FFFFFF"
  },
  137: {
    id: 137,
    name: "San Francisco Giants",
    shortName: "Giants",
    abbreviation: "SF",
    divisionId: 203,
    divisionName: "NL West",
    leagueId: 104,
    primaryColor: "#FD5A1E",
    secondaryColor: "#27251F",
    textColor: "#FFFFFF"
  },
  138: {
    id: 138,
    name: "St. Louis Cardinals",
    shortName: "Cardinals",
    abbreviation: "STL",
    divisionId: 205,
    divisionName: "NL Central",
    leagueId: 104,
    primaryColor: "#C41E3A",
    secondaryColor: "#0C2340",
    textColor: "#FFFFFF"
  },
  139: {
    id: 139,
    name: "Tampa Bay Rays",
    shortName: "Rays",
    abbreviation: "TB",
    divisionId: 201,
    divisionName: "AL East",
    leagueId: 103,
    primaryColor: "#092C5C",
    secondaryColor: "#8FBCE6",
    textColor: "#FFFFFF"
  },
  140: {
    id: 140,
    name: "Texas Rangers",
    shortName: "Rangers",
    abbreviation: "TEX",
    divisionId: 200,
    divisionName: "AL West",
    leagueId: 103,
    primaryColor: "#003278",
    secondaryColor: "#C0111F",
    textColor: "#FFFFFF"
  },
  141: {
    id: 141,
    name: "Toronto Blue Jays",
    shortName: "Blue Jays",
    abbreviation: "TOR",
    divisionId: 201,
    divisionName: "AL East",
    leagueId: 103,
    primaryColor: "#134A8E",
    secondaryColor: "#1D2D5C",
    textColor: "#FFFFFF"
  },
  120: {
    id: 120,
    name: "Washington Nationals",
    shortName: "Nationals",
    abbreviation: "WSH",
    divisionId: 204,
    divisionName: "NL East",
    leagueId: 104,
    primaryColor: "#AB0003",
    secondaryColor: "#142243",
    textColor: "#FFFFFF"
  },
  159: {
    id: 159,
    name: "American League All-Stars",
    shortName: "AL Stars",
    abbreviation: "AL",
    divisionId: 0,
    divisionName: "American League",
    leagueId: 103,
    primaryColor: "#0C2340",
    secondaryColor: "#C4CED4",
    textColor: "#FFFFFF"
  },
  160: {
    id: 160,
    name: "National League All-Stars",
    shortName: "NL Stars",
    abbreviation: "NL",
    divisionId: 0,
    divisionName: "National League",
    leagueId: 104,
    primaryColor: "#A71930",
    secondaryColor: "#E3D4AD",
    textColor: "#FFFFFF"
  }
};
